--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nicholass003/TopStats
build-by-default: true
branches:
- main
- stable
projects:
  TopStats:
    path: ""
    icon: "assets/icon.png"
    lint:
      phpstan: false
...
