--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nicholass003/TopStats
build-by-default: true
branches:
- main
projects:
  TopStats:
    path: ""
    icon: "assets/icon.png"
    libs:
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.3
      - src: Paroxity/Commando/Commando
        version: ^3.2.1
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^3.1.0
...
