name: TopStats
api: 5.36.0
version: 0.3.8
main: Nicholass003\TopStats\TopStats
author: nicholass003
website: https://github.com/nicholass003/TopStats
softdepend: ["BedrockEconomy", "EconomyAPI", "TopVoter"]
permissions:
  topstats.command:
    default: op
  topstats.command.autosave:
    default: op
  topstats.command.create:
    default: op
  topstats.command.delete:
    default: op
  topstats.command.list:
    default: op
  topstats.command.teleport:
    default: op
  topstats.command.type:
    default: op