name: TopStats
api: 5.3.0
version: 0.3.3
main: nicholass003\topstats\TopStats
author: nicholass003
website: https://github.com/nicholass003/TopStats
softdepend: ["BedrockEconomy", "EconomyAPI"]
permissions:
  topstats.command:
    default: op
  topstats.command.create:
    default: op
  topstats.command.delete:
    default: op
  topstats.command.list:
    default: op
  topstats.command.teleport:
    default: op
  topstats.command.type:
    default: op