# TopStats Configuration #
# Supported Databases:
# - json
database: "json"

# TopStats Format
# Leaderboard Max List:
max-list: 10
# Supported Models:
# - player
# - text
# Supported Data Types:
# - death
# - kill
# - block-break
# - block-place
# - change-skin
# - chat
# - consume
# - crafting
# - damage-dealt
# - damage-received
# - drop-item
# - emote
# - enchant
# - farm
# - heal
# - item-pickup
# - jump
# - kick
# Supported Tags:
# - death -> Number of Player Deaths
# - kill -> Number of Player Kills
# - block-break -> Number of Break Blocks
# - block-place -> Number of Block Placed
# - change-skin -> Number of Player Skin Changes
# - chat -> Number of Messages Sent
# - consume -> Number of Items Consumed
# - crafting -> Number of Items Crafted
# - damage-dealt -> Number of Damage Dealt
# - damage-received -> Number of Damage Received
# - drop-item -> Number of Items Dropped
# - emote -> Number of Player Emotes
# - enchant -> Number of Enchanted Items
# - farm -> Number of Planted Crops
# - heal -> Number of Health Recovered
# - item-pickup -> Number of Items Taken
# - jump -> Number of Player Jumps
# - kick -> Number of Player Kicked
# - player -> Player name
# - line -> New line
# Rank Tags:
# - rank_death -> Top Rank value of Player Deaths
# - rank_kill -> Top Rank value of Player Kills
# - rank_block-break -> Top Rank value of Break Blocks
# - rank_block-place -> Top Rank value of Block Placed
# - rank_change-skin -> Top Rank value of Player Skin Changes
# - rank_chat -> Top Rank value of Messages Sent
# - rank_consume -> Top Rank value of Items Consumed
# - rank_crafting -> Top Rank value of Items Crafted
# - rank_damage-dealt -> Top Rank value of Damage Dealt
# - rank_damage-received -> Top Rank value of Damage Received
# - rank_drop-item -> Top Rank value of Items Dropped
# - rank_emote -> Top Rank value of Player Emotes
# - rank_enchant -> Top Rank value of Enchanted Items
# - rank_farm -> Top Rank value of Planted Crops
# - rank_heal -> Top Rank value of Health Recovered
# - rank_item-pickup -> Top Rank value of Items Taken
# - rank_jump -> Top Rank value of Player Jumps
# - rank_kick-> Top Rank value of Player Kicked
models:
  player:
    death:
      title: "#{rank_death} {player}"
      description: "With deaths {death}"
    kill:
      title: "#{rank_kill} {player}"
      description: "With kills {kill}"
    block-break:
      title: "#{rank_block-break} {player}"
      description: "With break blocks {block-break}"
    block-place:
      title: "#{rank_block-place} {player}"
      description: "With place blocks {block-place}"
    change-skin:
      title: "#{rank_change-skin} {player}"
      description: "With skin changes {change-skin}"
    chat:
      title: "#{rank_chat} {player}"
      description: "With chats {chat}"
    consume:
      title: "#{rank_consume} {player}"
      description: "With item consumes {consume}"
    crafting:
      title: "#{rank_crafting} {player}"
      description: "With item crafted {crafting}"
    drop-item:
      title: "#{rank_drop-item} {player}"
      description: "With item dropped {drop-item}"
    damage-dealt:
      title: "#{rank_damage-dealt} {player}"
      description: "With damage dealt {damage-dealt}"
    damage-received:
      title: "#{rank_damage-received} {player}"
      description: "With damage received {damage-received}"
    emote:
      title: "#{rank_emote} {player}"
      description: "With emotes {emote}"
    enchant:
      title: "#{rank_enchant} {player}"
      description: "With enchants {enchant}"
    farm:
      title: "#{rank_farm} {player}"
      description: "With planted crops {farm}"
    heal:
      title: "#{rank_heal} {player}"
      description: "With health recovered {heal}"
    item-pickup:
      title: "#{rank_item-pickup} {player}"
      description: "With items taken {item-pickup}"
    jump:
      title: "#{rank_jump} {player}"
      description: "With jumps {jump}"
    kick:
      title: "#{rank_kick} {player}"
      description: "With kicked {kick}"
  text:
    death:
      title: ">> TOP DEATHS <<"
      description: "#{rank_death} {player} {death}{line}"
    kill:
      title: ">> TOP KILLS <<"
      description: "#{rank_kill} {player} {kill}{line}"
    block-break:
      title: ">> TOP BLOCK BREAKS <<"
      description: "#{rank_block-break} {player} {block-break}{line}"
    block-place:
      title: ">> TOP BLOCK PLACES <<"
      description: "#{rank_block-place} {player} {block-place}{line}"
    change-skin:
      title: ">> TOP SKIN CHANGES <<"
      description: "#{rank_change-skin} {player} {change-skin}{line}"
    chat:
      title: ">> TOP CHATS <<"
      description: "#{rank_chat} {player} {chat}{line}"
    consume:
      title: ">> TOP ITEM CONSUMES <<"
      description: "#{rank_consume} {player} {consume}{line}"
    crafting:
      title: ">> TOP ITEM CRAFTING <<"
      description: "#{rank_crafting} {player} {crafting}{line}"
    damage-dealt:
      title: ">> TOP DAMAGE DEALT <<"
      description: "#{rank_damage-dealt} {player} {damage-dealt}{line}"
    damage-received:
      title: ">> TOP DAMAGE RECEIVED <<"
      description: "#{rank_damage-received} {player} {damage-received}{line}"
    drop-item:
      title: ">> TOP ITEM DROPPED <<"
      description: "#{rank_drop-item} {player} {drop-item}{line}"
    emote:
      title: ">> TOP EMOTES <<"
      description: "#{rank_emote} {player} {emote}{line}"
    enchant:
      title: ">> TOP ENCHANTS <<"
      description: "#{rank_enchant} {player} {enchant}{line}"
    farm:
      title: ">> TOP FARMS <<"
      description: "#{rank_farm} {player} {farm}{line}"
    heal:
      title: ">> TOP HEALING <<"
      description: "#{rank_heal} {player} {heal}{line}"
    item-pickup:
      title: ">> TOP ITEMS TAKEN <<"
      description: "#{rank_item-pickup} {player} {item-pickup}{line}"
    jump:
      title: ">> TOP JUMPS <<"
      description: "#{rank_jump} {player} {jump}{line}"
    kick:
      title: ">> TOP KICKED <<"
      description: "#{rank_kick} {player} {kick}{line}"