# TopStats Configuration #
# Supported Databases:
# - json
database: "json"

# TopStats Format
# Leaderboard Max List:
max-list: 10
# Supported Models:
# - player
# - text
# Supported Data Types:
# - death
# - kill
# Supported Tags:
# - death -> Deaths value
# - kill -> Kills value
# - player -> Player name
# - line -> New line
# Rank Tags:
# - rank_death -> Top Rank value of deaths
# - rank_kill -> Top Rank value of kills
models:
  player:
    death:
      title: "#{rank_death} {player}"
      description: "With deaths {death}"
    kill:
      title: "#{rank_kill} {player}"
      description: "With kills {kill}"
  text:
    death:
      title: ">> TOP DEATHS <<"
      description: "#{rank_death} {player} {death}{line}"
    kill:
      title: ">> TOP KILLS <<"
      description: "#{rank_kill} {player} {kill}{line}"