# TopStats Configuration #
# Supported Databases:
# - json
database: "json"

# TopStats Format
# Leaderboard Max List:
max-list: 10
# Supported Models:
# - player
# - text
# Supported Data Types:
# - death
# - kill
# - block-break
# Supported Tags:
# - death -> Number of Player Deaths
# - kill -> Number of Player Kills
# - block-break -> Number of Break Blocks
# - block-place -> Number of Block Placed
# - player -> Player name
# - line -> New line
# Rank Tags:
# - rank_death -> Top Rank value of deaths
# - rank_kill -> Top Rank value of kills
models:
  player:
    death:
      title: "#{rank_death} {player}"
      description: "With deaths {death}"
    kill:
      title: "#{rank_kill} {player}"
      description: "With kills {kill}"
    block-break:
      title: "#{rank_block-break} {player}"
      description: "With break blocks {block-break}"
    block-place:
      title: "#{rank_block-place} {player}"
      description: "With place blocks {block-place}"
  text:
    death:
      title: ">> TOP DEATHS <<"
      description: "#{rank_death} {player} {death}{line}"
    kill:
      title: ">> TOP KILLS <<"
      description: "#{rank_kill} {player} {kill}{line}"
    block-break:
      title: ">> TOP BLOCK BREAKS <<"
      description: "#{rank_block-break} {player} {block-break}{line}"
    block-place:
      title: ">> TOP BLOCK PLACES <<"
      description: "#{rank_block-place} {player} {block-place}{line}"