# Database Configuration #
# Supported Databases:
# - mysql
database:
  type: mysql
  sqlite:
    file: data.sqlite
  mysql:
    host: 127.0.0.1
    username: root
    password: ""
    schema: your_schema